### ISSUE TITLE
PM: Update-Database -> Could not load type 'System.Data.OleDb.OleDbConnectionStringBuilder'...

### ISSUE THREAD

**Issue by ShamilS** [bubibubi/EntityFrameworkCore.Jet#19]
In the VS2017 Update 3 v.15.5.3 I'm trying to get through the following sample 

[Using Entity Framework Core with Jet in Traditional .Net Applications](https://github.com/bubibubi/EntityFrameworkCore.Jet/wiki/Using-Entity-Framework-Core-with-Jet-in-Traditional-.Net-Applications)

and I'm getting 

**Could not load type 'System.Data.OleDb.OleDbConnectionStringBuilder' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.**

error message in the Package Manager (PM) window while executing _Update-Database_ command.

Here are the steps to reproduce the issue:

1. In VS2017 create .NET Core 2.0 console app
2. in PM: _Install-Package Microsoft.EntityFrameworkCore -Version 2.0.2_
3. in PM: _Install-Package Microsoft.EntityFrameworkCore.Tools_
5. in PM: _Install-Package EntityFrameworkCore.Jet -Version 2.0.0_
6. In the project tree
     Dependencies 
	   -> NuGet
	   ->  EntityFrameworkCore.Jet (2.0.0) 
	      * Properties window set NoWarn = NU1701
7. Add class BloggingContext.cs  from the referred above sample, insert a code line

    using Microsoft.EntityFrameworkCore;

   in this class usings' part/code lines block and rebuild;

8. in PM: _Add-Migration MyFirstMigration_
9. in PM: _Update-Database_

System.TypeLoadException: Could not load type 'System.Data.OleDb.OleDbConnectionStringBuilder' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.Data.Jet.JetConnection.get_DataSource()
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.MigrateUsingConnection(IDiagnosticsLogger`1 diagnostics, IMigrator migrator, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load type 'System.Data.OleDb.OleDbConnectionStringBuilder' from assembly 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

?

**Comment by ShamilS** [comment]
The issue was opened by mistake. I should have used the sample with traditional .NET v.4.6.1+ apps and I have used it with .NET Core 2.0 console app.
