### ISSUE TITLE
Update-Database failed exception

### ISSUE THREAD

**Issue by vogelvision** [bubibubi/EntityFrameworkCore.Jet#24]
I'm using EntityFrameworkCore.Jet 2.1.0-preview5 and I ran  Add-Migration Initial and then ran Update-Database and I get this error:

Failed executing DbCommand (518ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SHOW TABLES WHERE NAME=''__EFMigrationsHistory''
System.Data.SyntaxErrorException: Syntax error: Missing operand after '__EFMigrationsHistory' operator.
   at System.Data.ExpressionParser.Parse()
   at System.Data.DataExpression..ctor(DataTable table, String expression, Type type)
   at System.Data.DataTable.Select(String filterExpression)
   at System.Data.Jet.JetStoreSchemaDefinition.JetStoreSchemaDefinitionRetrieve.GetDbDataReaderFromSimpleStatement(DbConnection connection, String commandText)
   at System.Data.Jet.JetStoreSchemaDefinition.JetStoreSchemaDefinitionRetrieve.TryGetDataReaderFromShowCommand(DbCommand command, DbDataReader& dataReader)
   at System.Data.Jet.JetCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteScalar(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Syntax error: Missing operand after '__EFMigrationsHistory' operator.

**Comment by jurgenvo** [comment]
@bubibubi Any chance this fix can be included in a new preview release on short notice?

**Comment by bubibubi** [comment]
I try to have a look at the beginning of the next week

**Comment by bubibubi** [comment]
Just released a preview 6

**Comment by jurgenvo** [comment]
@bubibubi Thanks for the quick help!
