### ISSUE TITLE
System.Data.OleDb.OleDbException (0x80040E10): No value given for one or more required parameters - (ADB repository using WIP release with EF Core 3.1.3)

### ISSUE THREAD

**Issue by lauxjpn** [bubibubi/EntityFrameworkCore.Jet#52]
@lauxjpn : I have tried with EF Core 3.1.3 and faced error: "System.Data.OleDb.OleDbException (0x80040E10): No value given for one or more required parameters." Could you give me some advice?
Note: I used your provider with ASPNET BoilerPlate fw.

_Originally posted by @ASCSolution in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-665571822_

---

@ASCSolution How does your `.UseJet()` call (and surrounding code) look like?
Also, please post the full stack trace of the exception, the Linq query that fails and the SQL that is being generated an logged by EF Core.

(You might want to create a new issue for this.)

_Originally posted by @lauxjpn in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-665580535_

**Comment by lauxjpn** [comment]
Here is my DbContext
```
public class VcbTrungGian1DbContext : AbpDbContext, IAbpPersistedGrantDbContext
    {
        /* Define an IDbSet for each entity of the application */
        public DbSet<PersistedGrantEntity> PersistedGrants { get; set; }
        public virtual DbSet<VCB1_PAYORDER> PAYORDERs { get; set; }
        public virtual DbSet<VCB1_REMITTANCE> REMITTANCEs { get; set; }

        public VcbTrungGian1DbContext(DbContextOptions<VcbTrungGian1DbContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VCB1_PAYORDER>().HasKey(c => new { c.SOGD });
            modelBuilder.Entity<VCB1_REMITTANCE>().HasKey(c => new { c.SOGD });
        }
    }
```

My connectionString
`Provider=Microsoft.ACE.OLEDB.12.0;Data Source=\\\\Server03\\Trunggian.mdb;Jet OLEDB:Database Password=password;`

This is my DbContextConfigurer
```
public static class VcbTrungGian1DbContextConfigurer
    {
        public static void Configure(DbContextOptionsBuilder<VcbTrungGian1DbContext> builder, string connectionString)
        {
            builder.UseJet(connectionString);
        }

        public static void Configure(DbContextOptionsBuilder<VcbTrungGian1DbContext> builder, DbConnection connection)
        {
            builder.UseJet(connection);
        }
    }
```

Init
```
//Vcb TrungGian 1
                Configuration.Modules.AbpEfCore().AddDbContext<VcbTrungGian1DbContext>(options =>
                {
                    if (options.ExistingConnection != null)
                    {
                        VcbTrungGian1DbContextConfigurer.Configure(options.DbContextOptions, options.ExistingConnection);
                    }
                    else
                    {
                        VcbTrungGian1DbContextConfigurer.Configure(options.DbContextOptions, options.ConnectionString);
                    }
                });
```

My test code to get all record from PAYORDER table
`var test = _payOrderRepository.GetAll().ToList();
`

Full stack trace
```
ERROR 2020-07-29 17:47:50,381 [7    ] Mvc.ExceptionHandling.AbpExceptionFilter - No value given for one or more required parameters.
System.Data.OleDb.OleDbException (0x80040E10): No value given for one or more required parameters.
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Jet.JetCommand.ExecuteDbDataReaderCore(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at EntityFrameworkCore.Jet.Storage.Internal.JetExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FastOne.Ipc.IPC.IpcTransactionsAppService.TestVcbPayOrder() in D:\02_PROJECT\SC_IPC\SOURCE\src\FastOne.Ipc.Application\IPC\IpcTransactionsAppService.cs:line 200
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

_Originally posted by @ASCSolution in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-665592386_

**Comment by lauxjpn** [comment]
@ASCSolution The configuration looks good as far as I can see. Please still add the Linq query and the generated SQL query (logged by EF Core).

_Originally posted by @lauxjpn in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-665725532_

**Comment by lauxjpn** [comment]
@lauxjpn I have tried to use LINQ queries directly and it worked. So I think the issue comes from IRepository of ABP fw. 

What I have tried:
```
            //Use IRepository of Abp fw
            var test1 = _payOrderRepository.GetAll();
            var testSql1 = test1.ToSql();

            //Use LINQ queries directly
            var test2 = _dbContextProvider.GetDbContext().PAYORDERs;
            var testSql2 = test2.ToSql();
```

`testSql1` and `testSql2` are the same query and I can copy it to run in MS Access. No problem with the generated query.

I can get data result from `test2` but cannot get from `test1`. 

This is the stack trace when get the result from `test1`
   ```
at System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Jet.JetCommand.ExecuteDbDataReaderCore(CommandBehavior behavior) in E:\Downloads\EntityFrameworkCore.Jet-3.1-preview\EntityFrameworkCore.Jet-3.1-preview\src\System.Data.Jet\JetCommand.cs:line 216
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at EntityFrameworkCore.Jet.Storage.Internal.JetExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) in E:\Downloads\EntityFrameworkCore.Jet-3.1-preview\EntityFrameworkCore.Jet-3.1-preview\src\EFCore.Jet\Storage\Internal\JetExecutionStrategy.cs:line 55
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

_Originally posted by @ASCSolution in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-666062677_

**Comment by lauxjpn** [comment]
>@ASCSolution The configuration looks good as far as I can see. Please still add ~~the Linq query and~~ the **generated SQL query (logged by EF Core)**.

In this case, please post both, the SQL query generated by the ABP repository and the SQL query generated directly by the context.
Because it is unclear at the moment, whether the error comes from a wrongly supplied parameter or from a wrongly formatted query, it is important that you post the queries that are being **[logged](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging) by EF Core, not using the `ToSql()` method**. (The `ToSql()` queries are parameterless and might therefore not be the exact queries that EF Core executes.) If you want, you can post both (so 4 SQL queries in total), but the SQL queries logged by EF Core are our primary focus at the moment.

You might want to add `.EnableSensitiveDataLogging()` and `.EnableDetailedErrors()` to your EF Core options builder for better logging output.

_Originally posted by @lauxjpn in https://github.com/bubibubi/EntityFrameworkCore.Jet/issues/34#issuecomment-666184307_

**Comment by horseyhorsey** [comment]
@lauxjpn Not all tables will give me this error using Linq. To get around that linq.select works.

Not sure how to check which column gives me issues in a table. Originally the table was scaffolded from older version 2.2 and I have Config for each table.

**Comment by horseyhorsey** [comment]
I found an `unmapped` property on the table. After adding `entity.Ignore(x => x.MyUnmappedProp);` in the builder it's fine.
